ARG STATICS_FROM=corpusops/node
ARG NGINX_VERSION=alpine-perl
ARG BASE=corpusops/nginx:$NGINX_VERSION

FROM $STATICS_FROM as statics
FROM $BASE         as nginx

ADD local/terra-front-deploy/prod/init.sh /code/init/
ADD local/terra-front-deploy/prod/etc/    /etc/
COPY --from=statics /code/public/ /usr/share/nginx/html/
ENTRYPOINT ["/code/init/init.sh"]
CMD ["nginx"]
