// Generated by corpusops from .ansible/playbooks/roles/terralegofront/templates/injection.js
window.REACT_APP_API_URL = "{{cops_terralego_back_url}}/api"
window.REACT_APP_BASE_URL = "{{cops_terralego_back_url}}"
window.REACT_APP_SOURCE_VECTOR_URL = "{{cops_terralego_vector_tiles_url}}"
